apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
  name: kafka-source
spec:
  consumerGroup: knative-group
  bootstrapServers:
  - my-cluster-kafka-bootstrap.demo.svc.cluster.local:9092
  topics:
  - orders
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: payment