apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/

patches:
- patch: |-
    - op: replace
      path: '/spec/template/spec/containers/0/env/0/value'
      value: "mongodb://mongodb-primary.demo.svc.clusterset.local:27017,mongodb-secondary.demo.svc.clusterset.local:27017,mongodb-arbiter.demo.svc.clusterset.local:27017/?replicaSet=replicaset&w=1&retryReads=true&retryWrites=true"
    - op: add
      path: '/spec/template/spec/containers/0/env/-'
      value:
        name: MP_MESSAGING_INCOMING_PAYMENTS_BOOTSTRAP_SERVERS
        value: my-cluster-kafka-bootstrap.demo.svc.clusterset.local:9092
    - op: add
      path: '/spec/template/spec/containers/0/env/-'
      value:
        name: MP_MESSAGING_INCOMING_ORDERS_BOOTSTRAP_SERVERS
        value: my-cluster-kafka-bootstrap.demo.svc.clusterset.local:9092
  target:
    kind: Deployment
    name: order
