# Note that the region and zone has been set to eu-central-1 / 1a for coolstore-b
# Please make the appropriate changes, if need be, accordingly
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../common/

patches:
- target:
    kind: StatefulSet
    name: yb-master
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/5/value
      value: "yb-master-0.coolstore-b.yb-masters.demo.svc.clusterset.local"
    - op: replace
      path: /spec/template/spec/containers/0/env/6/value
      value: "${CLUSTER_REGIONS[1]}"
    - op: replace
      path: /spec/template/spec/containers/0/env/9/value
      value: "${CLUSTER_REGIONS[1]}"
- target:
    kind: StatefulSet
    name: yb-tserver
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/5/value
      value: "yb-tserver-0.coolstore-b.yb-tservers.demo.svc.clusterset.local"
    - op: replace
      path: /spec/template/spec/containers/0/env/6/value
      value: "${CLUSTER_REGIONS[1]}"
    - op: replace
      path: /spec/template/spec/containers/0/env/7/value
      value: "${CLUSTER_REGIONS[1]}"
