apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/
- service.yaml

patches:
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: kafka-config
    data:
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://my-cluster-kafka-bootstrap.demo.svc.cluster.local:9092"
      KAFKA_CFG_MIN_INSYNC_REPLICAS: "1"
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: "1"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_KRAFT_CLUSTER_ID: ""
