apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: my-cluster-kafka-bootstrap
spec:
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
  selector:
    app: kafka
  type: ClusterIP