apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-primary
  name: mongodb-primary
spec:
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  selector:
    app: mongodb-primary
  type: ClusterIP
---
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceExport
metadata:
  name: mongodb-primary
