apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    k8s-app: kafka-exporter-monitor
  name: kafka-exporter-monitor
spec:
  podMetricsEndpoints:
  - interval: 15s
    port: tcp-prometheus
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-exporter