apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
  name: kafka-consumer
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: coolstore-a
    namespace: demo
  project: default
  source:
    directory:
      recurse: true
    path: kafka-consumer
    repoURL: http://gitea.infra.svc.cluster.local:3000/demo/coolstore.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 100