apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: yugabyte
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - list:
      elements:
      - cluster: coolstore-a
        values:
          namespace: demo
          overlay: coolstore-a
      - cluster: coolstore-b
        values:
          namespace: demo
          overlay: coolstore-b
      - cluster: coolstore-c
        values:
          namespace: demo
          overlay: coolstore-c
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "20"
      name: "{{cluster}}-yugabyte"
    spec:
      destination:
        namespace: "{{values.namespace}}"
        name: "{{cluster}}"
      project: default
      source:
        kustomize: {}
        path: yugabyte/overlays/multi-cluster/{{values.overlay}}
        repoURL: http://gitea.infra.svc.cluster.local:3000/demo/coolstore.git
        targetRevision: HEAD
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated: {}
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 100