apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

resources:
- ../../base/
- ../../create-databases/

patches:
- target:
    kind: StatefulSet
    name: yb-master
  patch: |-
    - op: add
      path: /metadata/labels/app.kubernetes.io~1part-of
      value: yugabyte
    - op: replace
      path: /spec/template/spec/containers/0/env/4/value
      value: "yb-master-0.yb-masters.demo.svc.cluster.local:7100"
    - op: replace
      path: /spec/template/spec/containers/0/env/5/value
      value: "yb-master-0.yb-masters.demo.svc.cluster.local"
    - op: replace
      path: /spec/template/spec/containers/0/env/7/value
      value: "1"
- target:
    kind: StatefulSet
    name: yb-tserver
  patch: |-
    - op: add
      path: /metadata/labels/app.kubernetes.io~1part-of
      value: yugabyte
    - op: add
      path: /metadata/labels/app.kubernetes.io~1instance
      value: yugabyte
    - op: replace
      path: /spec/template/spec/containers/0/env/4/value
      value: "yb-master-0.yb-masters.demo.svc.cluster.local:7100"
    - op: replace
      path: /spec/template/spec/containers/0/env/5/value
      value: "yb-tserver-0.yb-tservers.demo.svc.cluster.local"
