apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/

patches:
- patch: |-
    - op: replace
      path: "/spec/bootstrapServers"
      value: ["my-cluster-kafka-bootstrap.demo.svc.clusterset.local:9092"]
  target:
    kind: KafkaSource
    name: kafka-source

- patch: |-
    - op: replace
      path: "/spec/template/spec/containers/0/env/0/value"
      value: "my-cluster-kafka-bootstrap.demo.svc.clusterset.local:9092"
  target:
    kind: Service
    name: payment
