# this is a mirror of example-infinispan-site meant for the ServiceExport
apiVersion: v1
kind: Service
metadata:
  labels:
    app: infinispan-service-xsite
    clusterName: example-infinispan
    infinispan_cr: example-infinispan
  name: infinispan-a
spec:
  ports:
  - port: 7900
    protocol: TCP
    targetPort: 7900
  selector:
    app: infinispan-router-pod
    clusterName: example-infinispan
    infinispan_cr: example-infinispan
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceExport
metadata:
  name: infinispan-a
---
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceExport
metadata:
  name: example-infinispan