apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/

patches:
- patch: |-
    - op: replace
      path: "/spec/template/spec/containers/0/env/0/value"
      value: example-infinispan.demo.svc.clusterset.local:11222
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: MP_MESSAGING_OUTGOING_ORDERS_BOOTSTRAP_SERVERS
        value: my-cluster-kafka-bootstrap.demo.svc.clusterset.local:9092
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: CART_CLUSTER_NAME
        value: coolstore-c
  target:
    kind: Deployment
    name: cart
