apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

resources:
- ../../../base/
- serviceexports.yaml

patches:
- target:
    kind: StatefulSet
    name: yb-master
  patch: |-
    - op: add
      path: /metadata/labels/app.kubernetes.io~1part-of
      value: yugabyte
    - op: replace
      path: /spec/template/spec/containers/0/env/4/value
      value: "yb-master-0.coolstore-a.yb-masters.demo.svc.clusterset.local:7100,yb-master-0.coolstore-b.yb-masters.demo.svc.clusterset.local:7100,yb-master-0.coolstore-c.yb-masters.demo.svc.clusterset.local:7100"
    - op: replace
      path: /spec/template/spec/containers/0/env/8/value
      value: "10"
- target:
    kind: StatefulSet
    name: yb-tserver
  patch: |-
    - op: add
      path: /metadata/labels/app.kubernetes.io~1part-of
      value: yugabyte
    - op: add
      path: /metadata/labels/app.kubernetes.io~1instance
      value: yugabyte
    - op: replace
      path: /spec/template/spec/containers/0/env/4/value
      value: "yb-master-0.coolstore-a.yb-masters.demo.svc.clusterset.local:7100,yb-master-0.coolstore-b.yb-masters.demo.svc.clusterset.local:7100,yb-master-0.coolstore-c.yb-masters.demo.svc.clusterset.local:7100"
    - op: add
      path: /spec/template/spec/containers/0/resources/limits/hugepages-2Mi
      value: 100Mi