apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: my-cluster-kafka-1
spec:
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
    - name: controller
      port: 9093
      targetPort: 9093
  selector:
    kafka-instance: "1"
  type: ClusterIP
---
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceExport
metadata:
  name: my-cluster-kafka-1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: my-cluster-kafka-bootstrap
spec:
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
  selector:
    app: kafka
  type: ClusterIP
---
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceExport
metadata:
  name: my-cluster-kafka-bootstrap