apiVersion: v1 
kind: Secret
metadata:
  name: data-grid-identities
stringData:
  identities.yaml: |
    credentials:
    - username: user
      password: pass
      roles:
        - application
---
apiVersion: v1
kind: ConfigMap
metadata:
   name: data-grid-config
data:
  infinispan-config.yaml: |
    infinispan:
      server:
        endpoints:
          # https://infinispan.org/docs/stable/titles/security/security.html#configuring-server-authentication_endpoint-authentication
          endpoint:
            socketBinding: "default"
            securityRealm: "default"
            hotrodConnector:
              authentication:
                sasl:
                  serverName: "infinispan"
                  mechanisms:
                  - "SCRAM-SHA-512"
                  - "SCRAM-SHA-384"
                  - "SCRAM-SHA-256"
                  - "SCRAM-SHA-1"
                  - "DIGEST-SHA-512"
                  - "DIGEST-SHA-384"
                  - "DIGEST-SHA-256"
                  - "DIGEST-SHA"
                  - "DIGEST-MD5"
                  - "PLAIN"
                  qop:
                  - "auth"
            restConnector:
              authentication:
                mechanisms:
                - "DIGEST"
                - "BASIC"
                securityRealm: "default"
---
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: example-infinispan
  annotations:
    infinispan.org/monitoring: 'true'
spec:
  replicas: 1
  version: 8.4.1-1
  upgrades:
    type: Shutdown
  service:
    type: DataGrid
    container:
      storage: 2Gi
      ephemeralStorage: true
    sites:
      local:
        name: PRIMARY
        expose:
          type: ClusterIP
          port: 7900
        maxRelayNodes: 999
  security:
    endpointSecretName: data-grid-identities
    endpointEncryption:
        type: None
  container:
    extraJvmOpts: "-XX:NativeMemoryTracking=summary"
    cpu: "2000m:1000m"
    memory: "2Gi:1Gi"
  logging:
    categories:
      org.infinispan: debug
      org.jgroups: debug
      org.jgroups.protocols.TCP: error
      org.jgroups.protocols.relay.RELAY2: error
  configMapName: "data-grid-config"
  configListener:
    enabled: true
---
kind: Cache
apiVersion: infinispan.org/v2alpha1
metadata:
  name: cart
spec:
  clusterName: example-infinispan
  name: cart
  template: |
    distributedCache:
      mode: "SYNC"