apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argocd-sync
  name: argocd-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-sync
  strategy: {}
  template:
    metadata:
      labels:
        app: argocd-sync
    spec:
      containers:
      - image: ghcr.io/kwkoo/argocd-sync
        name: argocd-sync
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: argocd-sync
        #volumeMounts:
        #- name: certs
        #  readOnly: true
        #  mountPath: /etc/ssl/certs
        resources: {}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 6
      #volumes:
      #- name: certs
      #  secret:
      #    secretName: argocd-sync-certs
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: argocd-sync
  name: argocd-sync
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: argocd-sync
status:
  loadBalancer: {}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: argocd-sync
  name: argocd-sync
spec:
  port:
    targetPort: 8080
  to:
    name: argocd-sync
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
status: {}
